[Export]
offer_binder = false
# slider_server_url = "notebooks.vagusllc.com"
exclude = [
    "PlutoUI/src/Builtins.jl",
    "PlutoUI/src/Clock.jl",
    "PlutoUI/src/Combine.jl",
    "PlutoUI/src/Confirm.jl",
    "PlutoUI/src/DisplayTricks.jl",
    "PlutoUI/src/Images.jl",
    "PlutoUI/src/Layout.jl",
    "PlutoUI/src/MultiCheckBox.jl",
    "PlutoUI/src/PlutoUI.jl",
    "PlutoUI/src/RangeSlider.jl",
    "PlutoUI/src/Resource.jl",
    "PlutoUI/src/Scrubbable.jl",
    "PlutoUI/src/ScrubbableMatrix.jl",
    "PlutoUI/src/TableOfContents.jl",
    "PlutoUI/src/TerminalNotebook.jl",
    "PlutoUI/src/TransformedValue.jl",
    "PlutoUI/src/WebcamInput.jl",
    "PlutoUI/src/Wrapped.jl",
    "Viscoelastics/examples/BBModel.jl",
    "Hyperelastics/docs/examples/website.jl",
    "website_viscoelastics.jl",
]

[SliderServer]
port = 2345
host = "0.0.0.0"
# serve_static_export_folder = false

[Pluto]
[Pluto.evaluation]
capture_stdout = false
