[Export]
offer_binder = false
exclude = [
    "*/WebcamInput",
    "*/TransformedValue",
    "*/TerminalNotebook",
    "*/TableOfContents",
    "*/Scrubbable",
    "*/RangeSlider",
    "*/MultiCheckBox",
    "*/Layout",
    "*/Confirm",
    "*/Combine",
    "*/Clock",
    "*/Builtins"
]

[SliderServer]
port = 443
host = "0.0.0.0"
