[Export]
offer_binder = false
exclude = [
    "*/WebcamInput.jl",
    "*/TransformedValue.jl",
    "*/TerminalNotebook.jl",
    "*/TableOfContents.jl",
    "*/Scrubbable.jl",
    "*/RangeSlider.jl",
    "*/MultiCheckBox.jl",
    "*/Layout.jl",
    "*/Confirm.jl",
    "*/Combine.jl",
    "*/Clock.jl",
    "*/Builtin.jls"
]

[SliderServer]
port = 443
host = "0.0.0.0"
